name: Cargo Test (Live Endpoint)

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Display Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version

      - name: Build and test
        run: |
          cargo test --verbose --test live_endpoint
